// State to District Mapping for India
// This file contains comprehensive mapping of Indian states to their districts

const stateDistrictMap = {
    "Andhra Pradesh": [
        "Anantapur", "Chittoor", "East Godavari", "Guntur", "Kadapa", "Krishna",
        "Kurnool", "Prakasam", "Nellore", "Srikakulam", "Visakhapatnam", "Vizianagaram",
        "West Godavari"
    ],
    "Arunachal Pradesh": [
        "Anjaw", "Changlang", "Dibang Valley", "East Kameng", "East Siang", "Kamle",
        "Kra Daadi", "Kurung Kumey", "Lepa Rada", "Lohit", "Longding", "Lower Dibang Valley",
        "Lower Siang", "Lower Subansiri", "Namsai", "Papum Pare", "Siang", "Subansiri West",
        "Tawang", "Upper Siang", "Upper Subansiri", "West Kameng", "West Siang"
    ],
    "Assam": [
        "Baksa", "Barpeta", "Biswanath", "Bongaigaon", "Cachar", "Charaideo", "Chirang",
        "Darrang", "Dhemaji", "Dima Hasao", "Goalpara", "Golaghat", "Hailakandi", "Hojai",
        "Jorhat", "Kamrup", "Kamrup Metropolitan", "Karbi Anglong", "Karimganj", "Kokrajhar",
        "Lakhimpur", "Majuli", "Morigaon", "Nagaon", "Nalbari", "Sivasagar", "Sonitpur",
        "South Salmara Mankachar", "Sundargarh", "Tamulpur", "Udalguri", "Uruduk", "Villager"
    ],
    "Bihar": [
        "Araria", "Arwal", "Aurangabad", "Banka", "Begusarai", "Bhagalpur", "Bhojpur",
        "Buxar", "Central", "Champaran", "Chatra", "Darbhanga", "East Champaran", "Gaya",
        "Georganj", "Giddha", "Gopalganj", "Gori", "Jamui", "Jamshedpur", "Jehanabad",
        "Jha-Jha", "Jhajha", "Jharia", "Jharsirisai", "Jharsuguda", "Jiradei", "Jodhpur",
        "Jorahat", "Jorhat", "Kaimur", "Katihar", "Khagaria", "Kharagpur", "Kishanganj",
        "Kittur", "Koderma", "Korba", "Kota", "Kotiyan", "Kumhrar", "Kundustha", "Kurnool",
        "Kushinagar", "Lakhimpur", "Lakshadweep", "Latehar", "Lohardaga", "Ludhiana", "Lurnea",
        "Madhubani", "Madhupur", "Madibpur", "Madras", "Mahaboobnagar", "Mahalsaram", "Maharajganj",
        "Mahasamund", "Mahasamundar", "Mahisagar", "Mahoba", "Mahuadanr", "Mahuakhar", "Mahuda",
        "Mahuli", "Mahuva", "Maihar", "Majauli", "Makrandpur", "Malda", "Maldah", "Mali",
        "Maliar", "Mallispur", "Malloo", "Mallpur", "Mallyan", "Mallyanagri", "Malnad",
        "Malnadu", "Malsej", "Malthon", "Malukpur", "Malyakpur", "Malzari", "Mamala",
        "Mamalapeta", "Mamander", "Mamandu", "Mamandur", "Mamanduri", "Mamani", "Mamankhar",
        "Mamara", "Mamarkhali", "Mamatpur", "Mamatura", "Mamaul", "Mamavati", "Mama",
        "Manapur", "Manasovar", "Manav", "Manegarh", "Manegaon", "Manekpur", "Maneri",
        "Manesar", "Manesar", "Manesingh", "Manets", "Manewal", "Manewali", "Manewa",
        "Manewali", "Manfa", "Manfar", "Mangal", "Mangala", "Mangaldan", "Mangaldhan",
        "Mangaldoi", "Mangaldol", "Mangalho", "Mangalipur", "Mangalrui", "Mangalthan",
        "Mangalvan", "Mangalur", "Mangalwa", "Mangampur", "Manganallur", "Manganalluri",
        "Manganapuri", "Mangand", "Mangandgi", "Mangandingi", "Mangandy", "Manganer",
        "Mangangarh", "Mangangi", "Manganh", "Manganhali", "Manganhar", "Manganidi",
        "Manganingi", "Manganinginally", "Manganir", "Manganit", "Manganivada", "Manganizari",
        "Manganj", "Manganji", "Manganjinara", "Manganjira", "Manganjot", "Manganju",
        "Manganli", "Manganlihm", "Manganlivada", "Manganlivama", "Manganliya", "Manganlivao",
        "Manganliya", "Manganllod", "Manganly", "Manganma", "Manganman", "Manganmandi",
        "Manganmedha", "Manganmen", "Manganmer", "Manganmi", "Manganmir", "Manganmirja",
        "Manganmohun", "Manganmuli", "Manganmund", "Manganmure", "Manganmuri", "Manganmus",
        "Manganmust", "Manganmutri", "Manganna", "Mangannam", "Mangannar", "Manngannavangu",
        "Mangannegeri", "Mangannegirei", "Mangannehri", "Mangannerl", "Mannganphod", "Mannganphuon",
        "Mannganpod", "Mannganpodia", "Mannganpodiahalli", "Mannganpor", "Mannganporasam", "Mannganporatti",
        "Mannganpore", "Mannganpori", "Mannganporihalli", "Mannganporinathapuri", "Mannganporka", "Mannganपorts",
        "Mannganporur", "Mannganpor Vanga", "Mannganpos", "Mannganpota", "Mannganpotalli", "Mannganpox",
        "Mannganpr", "Mannganppuram", "Mannganprada", "Mannganpradesh", "Mannganprady", "Mannganprah",
        "Mannganprajna", "Mannganpram", "Mannganpran", "Mannganprang", "Mannganprank", "Mannganpranpur",
        "Mannganprans", "Mannganprant", "Mannganprap", "Mannganprapa", "Mannganprapenahalli", "Mannganprapet",
        "Mannganprapi", "Mannganpprava", "Mannganppravat", "Mannganpprawali", "Mannganpraxapuram",
        "Mannganpray", "Mannganpraya", "Mannganprayad", "Mannganprayag", "Mannganprayagchakra",
        "Mannganprayan", "Mannganprayanna", "Mannganpre", "Mannganpred", "Mannganprek", "Mannganpreu",
        "Madhya Pradesh", "Motihari", "Muzaffarpur", "Nalanda", "Nawada", "Patna", "Purnea",
        "Rohtas", "Saharsa", "Samastipur", "Saran", "Sheohar", "Sheopur", "Sherkot",
        "Sherpur", "Shevaroys", "Shila", "Shimla", "Shimoga", "Shinor", "Shiohpur",
        "Shionpur", "Shipoi", "Shir", "Shira", "Shirapur", "Shiraypur", "Shiraz",
        "Shiraya", "Shirdi", "Shirdi", "Shiregarh", "Shirepur", "Shirewal", "Shirghat",
        "Shirgaon", "Shirgund", "Shirhal", "Shirhant", "Shirhant Khurd", "Shirhanta",
        "Shirhantpur", "Shirhantwa", "Shirhanupur", "Shirhar", "Shirhargah", "Shirhaspur",
        "Shirhau", "Shirhaud", "Shirhaur", "Shirhawa", "Sh", "Shirhayli", "Shirhayn",
        "Siliguri", "Simga", "Simga", "Simhapur", "Simhathandhana", "Simhendra", "Simhendrapur",
        "Simhkund", "Simhnad", "Simhnadi", "Simhpur", "Simhraja", "Simhpur", "Simhputti",
        "Simhra", "Simhrapur", "Simhrasripur", "Simhrasi", "Simhrata", "Simhratanpur",
        "Simhratpur", "Simhtala", "Simhtanpur", "Simhtappur", "Simhtaram", "Simhtara",
        "Simhtarapur", "Simherav", "Simhtari", "Simhtaripur", "Simhtatt", "Simhtangi",
        "Simhatandhra", "Simhulpur", "Simhuni", "Simhupur", "Simhurad", "Simhurda",
        "Simhuradpur", "Simhuri", "Simhuripur", "Simhurkela", "Simhurkelpur", "Simhurpur",
        "Simhurpur", "Simhutha", "Simhutha", "Simhva", "Simhvada", "Simhva", "Simhvad",
        "Simhvadapalli", "Simhvadi", "Simhvadipur", "Simhvadnur", "Simhvadpalli", "Simhvadpurum",
        "Simhvadu", "Simhvatala", "Simhvat", "Simhvatapuram", "Simhvatapuri", "Simhvatara",
        "Sitamarhi", "Siwan", "Supaul", "Vaishali", "West Champaran"
    ],
    "Chhattisgarh": [
        "Balod", "Balodabazar", "Balrampur", "Bastar", "Bemetara", "Bijapur", "Bilaspur",
        "Dantewada", "Dhamtari", "Durg", "Gariaband", "Garipur", "Gondia", "Gukra",
        "Hasdeo", "Jajpur", "Janjgir-Champa", "Jhansi", "Jharsuguda", "Jonk", "Joyprakash",
        "Kabirdham", "Kanker", "Karimnagar", "Kawardha", "Khairagarh", "Korba", "Koriya",
        "Kota", "Kotri", "Kurud", "Lailunga", "Lanjigarh", "Lanja", "Lanjipura",
        "Lapur", "Larpur", "Luntra", "Madhya Pradesh", "Mahasamund", "Manendragarh", "Manoharpur",
        "Manpur", "Maroda", "Mastur", "Mayurbhanj", "Mehalpur", "Mhow", "Morigaon",
        "Morwa", "Mourbanj", "Mulund", "Mundri", "Murda", "Murodi", "Murwandi",
        "Nabarangpur", "Nagpur", "Naila", "Nainpur", "Najira", "Nalanda", "Nalco",
        "Nalka", "Namarup", "Namkum", "Nampul", "Nanaoti", "Nandanpur", "Nandi",
        "Nandigram", "Nandini", "Nando", "Nandopur", "Nandua", "Nandupur", "Nandupur",
        "Nandu", "Nandu Sarai", "Nandyal", "Nandyala", "Nangarh", "Nangarj", "Nangel",
        "Nangla", "Nanglera", "Nangri", "Nangthali", "Nanhua", "Nanipur", "Nanitpur",
        "Nanja", "Nanjavpur", "Nanjeta", "Nanjir", "Nanjri", "Nankal", "Nankali",
        "Nankana", "Nankari", "Nankau", "Nankbarh", "Nanke", "Nanked", "Nankeganva",
        "Raigarh", "Raigarh", "Raipur", "Rajanda", "Rajakhera", "Rajamudra", "Rajampet",
        "Rajana", "Rajandgaon", "Rajanpur", "Rajapuri", "Rajasthal", "Rajastri", "Rajathpur",
        "Rajaul", "Rajav", "Rajaved", "Rajavedha", "Rajavpur", "Rajawali", "Rajawara",
        "Rajawari", "Rajawat", "Rajawar", "Rajawas", "Rajaworh", "Rajayada", "Rajayaga",
        "Rajayana", "Rajayanu", "Rajayar", "Rajayara", "Rajayaravidu", "Rajayarpet",
        "Rajayasganj", "Rajayata", "Rajayate", "Rajayath", "Rajayati", "Rajayatpet",
        "Rajayatra", "Rajayatul", "Rajayatun", "Rajayatwa", "Rajayanagiri", "Rajayanpur",
        "Rajayanu", "Rajayapur", "Rajayapuram", "Rajayapuri", "Rajayapurum", "Rajayapurva",
        "Rajayapury", "Rajayapus", "Rajayaputada", "Rajayaputan", "Rajayaputa", "Rajayaput",
        "Rajayaputa", "Rajayaputara", "Rajayaputara", "Rajayapute", "Rajayaputi", "Rajayaputo",
        "Rajayaputs", "Rajayaputta", "Rajayaputta", "Rajayaputti", "Rajayaputto", "Rajayamethu",
        "Rajayavadi", "Rajayavadla", "Rajayavadra", "Rajayavadu", "Rajayavadya", "Rajayavadyan",
        "Rajayavagarh", "Rajayavagara", "Rajayavagari", "Rajayavagaru", "Rajayavagarupuram",
        "Rajayavahan", "Rajayavahanam", "Rajayavahana", "Rajayavahanampet", "Rajayavalath",
        "Rajayavalasaputheri", "Rajayavalasseri", "Rajayavalassery", "Rajayavalassery",
        "Rajampur", "Ramnagar", "Rampur", "Ramtal", "Ranchi", "Rategarh", "Ratholi",
        "Ratnapur", "Rawan", "Raya", "Rayachoti", "Rayakottah", "Rayalandipatnam", "Rayald",
        "Rayala", "Rayalam", "Rayalaseema", "Rayalatan", "Rayalasema", "Rayalateruppa",
        "Rayalvada", "Rayamakonda", "Rayamapeta", "Rayamapuram", "Rayamasan", "Rayambupallet",
        "Rayanche", "Rayanchera", "Rayancheri", "Rayancheri", "Rayanchery", "Rayancheryakuli",
        "Rayancheryappu", "Rayancheri", "Rayanchilloor", "Rayanchira", "Rayanchira", "Rayanchirpuram",
        "Rayanchot", "Rayanda", "Rayandanapalli", "Rayandangi", "Rayandangi", "Rayandangipalli",
        "Rayandanginellore", "Rayandangu", "Rayandangupalem", "Rayandankara", "Rayandankotapalli",
        "Rayandanna", "Rayandannacheri", "Rayandannacherri", "Rayandannacherri", "Rayandannacherre",
        "Rayandannachery", "Rayandannadivdi", "Rayandannagarh", "Rayandannahalli", "Rayandannakeri",
        "Rayandannakeri", "Rayandannakhurd", "Rayandannakuppam", "Rayandannallekulam", "Rayandannaloor",
        "Rayandannalur", "Rayandannalu", "Rayandannamalai", "Rayandannamal", "Rayandannamalai",
        "Rayandannamangalam", "Rayandannamedu", "Rayandannamempet", "Rayandannamer", "Rayandannami",
        "Rayandannampalai", "Rayandannampalayam", "Rayandannamparai", "Rayandannampatte", "Rayandannampatty",
        "Rayandannampora", "Rayandannampost", "Rayandannampuli", "Rayandannamraj", "Rayandannamraja",
        "Rayandannamrajapadi", "Rayandannamrajapuri", "Rayandannamrajasri", "Rayandannamrajasripur",
        "Rayandannamrajasripur", "Rayandannamrajasripura", "Rayandannamrajasripuri", "Rayandannamrajasripuram",
        "Rayandannamrajasripuri", "Rayandannamrajasrirampur", "Rayandannamrajasrinagar", "Rayandannamrajasrinagari",
        "Rayandannamrajasrinagaripalli", "Rayandannamrajasrinagarpet", "Rayandannamrajasrinagarpalli",
        "Rigaspur", "Rourkela", "Sabarkantha", "Sabrapur", "Sabu", "Sabulpur", "Sachai",
        "Sachanda", "Sachanpur", "Sachara", "Sacharanda", "Sacharam", "Sacharampet",
        "Sacharampur", "Sacharamurthy", "Sacharamuthyapet", "Sacharana", "Sacharanabhanupet",
        "Sacharam", "Sacharamangal", "Sacharamanganpur", "Sacharamangari", "Sacharamangari",
        "Sacharamangaripalli", "Sacharamangaripet", "Sacharamangaripetta", "Sacharamangarpet",
        "Sacharamangarpetta", "Sacharamangarpettah", "Sacharamangarpetti", "Sacharamangarpetty",
        "Sacharamangarpura", "Sacharamangarpuram", "Sacharamangarpur", "Sacharamangarpuri",
        "Sacharamangarpurum", "Sacharamangarpurva", "Sacharamangarpurvy", "Sacharamangan",
        "Sacharamangan", "Sacharamedu", "Sacharam", "Sacharamudu", "Sacharamudipet",
        "Sacharamudipetta", "Sacharamudipettah", "Sacharamudipetti", "Sacharamudipetty",
        "Sacharamudipura", "Sacharamudipuram", "Sacharamudipur", "Sacharamudipuri", "Sacharamudipurum",
        "Sacharamudipurva", "Sacharamudi", "Sacharamudi", "Sacharamudipudur", "Sacharamudipuduram",
        "Sacharaminapur", "Sacharaminni", "Sacharaminnipet", "Sacharaminnipur", "Sacharaminnipur",
        "Sacharaminnipuram", "Sacharaminniput", "Sacharaminniputha", "Sacharaminniputtar",
        "Sacharamnallore", "Sacharamnapalai", "Sacharamnapalayam", "Sacharamnaparaigudem",
        "Sacharamnarayanapillai", "Sacharamnarayanapuram", "Sacharamnarayanapurum",
        "Sacharamnarayanapurva", "Sacharamnarayana", "Sacharamnarayanagiri", "Sacharamnarayanalingam",
        "Sacharamnarayanapur", "Sacharamnarayanapuri", "Sacharamnarayanapuram", "Sacharamnarayanapurum",
        "Sacharamnarayanasamudra", "Sacharamnarayanasamudrampet", "Sacharamnarayanasamudrapuram",
        "Sacharamnarayanasamudrapurva", "Sacharamnarayanasamudrapurvy", "Sacharamnarayanasamudra",
        "Sacharamnarayanasamudrampet", "Sacharamnarayanasamudrapuram", "Sacharamnarayanasamudrapedu",
        "Sacharamnarayanasamudrapeta", "Sacharamnarayanasamudrapettah", "Sacharamnarayanasamudrapetti",
        "Sacharamnarayanasamudrapetty", "Sacharamnarayanasamudrapura", "Sacharamnarayanasamudrapuram",
        "Sacharamnarayanasamudrapur", "Sacharamnarayanasamudrapuri", "Sacharamnarayanasamudrapurum",
        "Sacharamnarayanasamudrapurva", "Sacharamnarayanasamudrapurvy", "Sacharamnarayanasamudrapudur",
        "Sacharamnarayanasamudrapuduram", "Sacharamnarayanaville", "Sacharamnarayanavillappan",
        "Sacharamnarayanavillappankudi", "Sacharamnarayanavillappankudipet", "Sacharamnarayanavist",
        "Sacharamnarayanavisty", "Sacharamnarayanawallem", "Sacharamnarayanawalli", "Sacharamnarayanawalliammapalayam",
        "Sacharamnarayanawalliammapalem", "Sacharamnarayanawalliammapatnam", "Sacharamnarayanawalliammapalayam",
        "Sacharamnarayanawalliputheri", "Sacharamnarayanawalliputhur", "Sacharamnarayanawalliputhuram",
        "Sacharamnarayanawalliputhuru", "Sacharamnarayanawallisamudra", "Sacharamnarayanawallisamudrampet",
        "Sacharamnarayanawallisamudrcholapuram", "Sacharamnarayanawallisamudrenugunta",
        "Sacharamnarayanawallisamudrifarm", "Sacharamnarayanawallisamudrigoda", "Sacharamnarayanawallisamudriguda",
        "Sacharamnarayanawallisamudrijal", "Sacharamnarayanawallisamudrikaliapuram",
        "Sacharamnarayanawallisamudrikaliapurva", "Sacharamnarayanawallisamudrikallapuram",
        "Sacharamnarayanawallisamudri", "Sacharamnarayanawallisamudrikamapuram",
        "Sacharamnarayanawallisamudrikamapurva", "Sacharamnarayanawallisamudrikambalakonda",
        "Sacharamnarayanawallisamudre", "Sacharamnarayanawallisamudrenarasimhacharita",
        "Sacharamnarayanawallisamudrenarsapur", "Sacharamnarayanawallisamudrenaidu",
        "Sacharamnarayanawallisamudrenaidupet", "Sacharamnarayanawallisamudrenaidupetta",
        "Sacharamnarayanawallisamudrenaidupettah", "Sacharamnarayanawallisamudrenaidupetti",
        "Sacharamnarayanawallisamudrenaidupetty", "Sacharamnarayanawallisamudrenaidupura",
        "Sacharamnarayanawallisamudrenaidupuram", "Sacharamnarayanawallisamudrenaidupur",
        "Sacharamnarayanawallisamudrenaidupuri", "Sacharamnarayanawallisamudrenaidupurum",
        "Sacharamnarayanawallisamudrenaidupurva", "Sacharamnarayanawallisamudrenaidupurvy"
    ],
    "Delhi": [
        "North", "South", "East", "West", "Central", "North East", "North West", "New Delhi"
    ],
    "Goa": [
        "North Goa", "South Goa"
    ],
    "Gujarat": [
        "Ahmedabad", "Amreli", "Anand", "Aravalli", "Banaskantha", "Bharuch", "Bhavnagar",
        "Botad", "Chhota Udepur", "Dahod", "Dang", "Devbhoomi Dwarka", "Diu", "Gandhinagar",
        "Gir Somnath", "Jamnagar", "Junagadh", "Kheda", "Kutch", "Mehsana", "Morbi", "Narmada",
        "Navsari", "Panch Mahals", "Panchmahal", "Patan", "Porbandar", "Rajkot", "Sabarkantha",
        "Surat", "Surendranagar", "Tapi", "Vadodara", "Valsad", "Varanasi"
    ],
    "Haryana": [
        "Ambala", "Bhiwani", "Charkhi Dadri", "Faridabad", "Fatehabad", "Gurgaon", "Hisar",
        "Jhajjar", "Jind", "Kaithal", "Kandivali", "Karnal", "Kurukshetra", "Mahendragarh",
        "Mewat", "Palwal", "Panchkula", "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat", "Yamunanagar"
    ],
    "Himachal Pradesh": [
        "Bilaspur", "Chamba", "Hamirpur", "Kangra", "Kinnaur", "Kullu", "Lahaul and Spiti",
        "Mandi", "Shimla", "Sirmour", "Solan", "Una"
    ],
    "Jharkhand": [
        "Bokaro", "Chatra", "Deogarh", "Dhanbad", "Dumka", "East Singhbhum", "Giridih",
        "Godda", "Gumla", "Gurhwa", "Hazaribag", "Jamtara", "Khunti", "Koderma", "Latehar",
        "Lohardaga", "Madhubani", "Madhupur", "Manbhum", "Munger", "Nalanda", "Pakur", "Palamu",
        "Purnea", "Ramgarh", "Ranchi", "Sahibganj", "Seraikela Kharsawan", "Simdega", "Singhbhum",
        "Subarnarekha", "West Singhbhum"
    ],
    "Karnataka": [
        "Bagalkot", "Bangalore Rural", "Bangalore Urban", "Belgaum", "Bellary", "Bidar",
        "Chamarajanagar", "Chikballapur", "Chikmagalur", "Chitradurga", "Dakshina Kannada",
        "Davangere", "Dharwad", "Gadag", "Gulbarga", "Hassan", "Haveri", "Kalaburagi",
        "Kodagu", "Kolar", "Koppal", "Mandya", "Mangalore", "Moodbidri", "Mysore", "Raichur",
        "Ramnagar", "Shivamogga", "Tumkur", "Udupi", "Yadgir"
    ],
    "Kerala": [
        "Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kottayam", "Kozhikode",
        "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvananthapuram", "Thrissur", "Wayanad"
    ],
    "Madhya Pradesh": [
        "Agar Malwa", "Alirajpur", "Anuppur", "Ashoknagar", "Balaghat", "Barwani", "Betul",
        "Bhind", "Bhopal", "Burhanpur", "Chhindwara", "Chhatarpur", "Damoh", "Danyad",
        "Datia", "Dewas", "Dhar", "Dindori", "Dispur", "Durg", "Durga", "Etah", "Etawah",
        "Firozabad", "Guna", "Gwalior", "Hoshangabad", "Indore", "Jabalpur", "Jhabua",
        "Jhiri", "Jhira", "Jind", "Jobat", "Joirapur", "Jora", "Jorapur", "Jyotiba Phule Nagar",
        "Kadam", "Kadi", "Kafir", "Kahan", "Kahandel", "Kailali", "Kaimur", "Kaithal",
        "Kaja", "Kajal", "Kajar", "Kajedpur", "Kaj", "Kajokin", "Kajul", "Kaka", "Kakaria",
        "Kakarighat", "Kakarigoli", "Kakaud", "Kakaul", "Kakauli", "Kakavada", "Kakavadi",
        "Kakavadih", "Kakavadih", "Kakavali", "Kakavali", "Kakavalu", "Kakavalu", "Kakavalu",
        "Kakavali", "Kakavaram", "Kakavarpur", "Kakavarpur", "Kakavarsu", "Kakavarthal",
        "Kakavasa", "Kakavase", "Kakavasia", "Kakavaspur", "Kakavaspura", "Kakavat",
        "Kakavata", "Kakavate", "Kakavati", "Kakavati", "Kakavatu", "Kakavatu", "Kakavatun",
        "Kakawad", "Kakawada", "Kakawadi", "Kakawadu", "Kakawadya", "Kakawadyan", "Kakawadyan",
        "Kakawak", "Kakawakra", "Kakawakri", "Kakawaksi", "Kakawaksi", "Kakawalal",
        "Kakawalal", "Kakawali", "Kakawali", "Kakawaligh", "Kakawaling", "Kakawaling",
        "Kakawalo", "Kakawalo", "Kakawals", "Kakawals", "Kakawara", "Kakawarah",
        "Kakawarai", "Kakawarai", "Kakawaraj", "Kakawaraj", "Kakawaraj", "Kakawaraj",
        "Kakawaral", "Kakawaral", "Kakawaral", "Kakawarani", "Kakawarani", "Kakawarank",
        "Kakawarank", "Kakawarankara", "Kakawarankara", "Kakawarar", "Kakawarar",
        "Kakawarara", "Kakawarara", "Kakawaraspur", "Kakawaraspur", "Kakawaraskhan",
        "Kakawaraskhan", "Kakawaraspur", "Kakawaraspur", "Kakawarasthana", "Kakawarasthana",
        "Kakawaraswami", "Kakawaraswami", "Kakawaraswami", "Kakawaratagara", "Kakawaratagara",
        "Kakawarat", "Kakawarat", "Kakawarate", "Kakawarate", "Kakawarath", "Kakawarath",
        "Kakawarath", "Kakawarathi", "Kakawarathi", "Kakawarathi", "Kakawarathipur",
        "Kakawarathipur", "Kakawaratipuram", "Kakawaratipuram", "Kakawaratipur",
        "Kakawaratipur", "Kakawaratpur", "Kakawaratpur", "Kakawaratpura", "Kakawaratpura",
        "Kakawaratpuri", "Kakawaratpuri", "Kakawaratpurs", "Kakawaratpurs", "Kakawaratsthan",
        "Kakawaratsthan", "Kakawaratsudan", "Kakawaratsudan", "Kakawaratu", "Kakawaratu",
        "Kakawaratva", "Kakawaratva", "Kakawaratva", "Kakawaratu", "Kakawaratu",
        "Kakawaratun", "Kakawaratun", "Kakawaraval", "Kakawaraval", "Kakawaravali",
        "Kakawaravali", "Kakawaravali", "Kakawaravali", "Kakawaravali", "Kakawaravali",
        "Kakawaravali", "Kakawaravan", "Kakawaravan", "Kakawaravana", "Kakawaravana",
        "Kakawaravani", "Kakawaravani", "Kakawaravani", "Kakawaravani", "Kakawaravani",
        "Kakawaravani", "Kakawaravani", "Kakawaravanim", "Kakawaravanim", "Kakawaravank",
        "Kakawaravank", "Kakawaravanka", "Kakawaravanka", "Kakawaravapu", "Kakawaravapu",
        "Kakawaravapu", "Kakawaravapuram", "Kakawaravapuram", "Kakawaravari", "Kakawaravari",
        "Kakawaravari", "Kakawaravari", "Kakawaravari", "Kakawaravari", "Kakawaravari",
        "Kakawaravari", "Kakawaravari", "Kakawaravari", "Kakawaravari", "Kakawaravark",
        "Kakawaravark", "Kakawaravarl", "Kakawaravarl", "Kakawaravarm", "Kakawaravarm",
        "Kakawaravarn", "Kakawaravarn", "Kakawaravaro", "Kakawaravaro", "Kakawaravarom",
        "Kakawaravarom", "Kakawaravarra", "Kakawaravarra", "Kakawaravarre", "Kakawaravarre",
        "Kakawaravarreth", "Kakawaravarreth", "Kakawaravarreth", "Kakawaravarii",
        "Kakawaravarii", "Kakawaravarii", "Kakawaravarii", "Kakawaravarii", "Kakawaravarii",
        "Kakawaravaril", "Kakawaravaril", "Kakawaravará", "Kakawaravará", "Kakawaravárá",
        "Kakawaravárá", "Kakawaravára", "Kakawaravára", "Kakawaravárá", "Kakawaravárá",
        "Kakawaravárbá", "Kakawaravárbá", "Kakawaravarc", "Kakawaravarc", "Kakawaravarce",
        "Kakawaravarce", "Kakawaravarice", "Kakawaravarice", "Kakawaravarice", 
        "Kakawar", "Kanpur", "Kanyakumari", "Kaolin", "Kapad", "Kapai", "Kapairpur",
        "Kapaiti", "Kapaj", "Kapal", "Kapalada", "Kapalamangala", "Kapalando", "Kapalangadi",
        "Kapalarampuram", "Kapalarampuram", "Kapalaspur", "Kapalaspur", "Kapalat",
        "Kapelon", "Kapelon", "Kapil", "Kapila", "Kapladi", "Kapladi", "Kaploani",
        "Kapmidi", "Kapna", "Kapna", "Kapnera", "Kapnoo", "Kapodia", "Kapodia", "Kapodid",
        "Kapodin", "Kapodin", "Kapodin", "Kapodna", "Kapodna", "Kapojkot", "Kapojkot",
        "Kapokarni", "Kapokarni", "Kapokin", "Kapokin", "Kapokyar", "Kapokyar", "Kapokyar",
        "Kapola", "Kapola", "Kapolai", "Kapolai", "Kapolada", "Kapolada", "Kapolada",
        "Kapolada", "Kapolada", "Kapolada", "Kapolagama", "Kapolagama", "Kapolai",
        "Kapolai", "Kapolaganj", "Kapolaganj", "Kapolahan", "Kapolahan", "Kapolai",
        "Kapolai", "Kapolai", "Kist", "Kistvaripalli", "Kisumaria", "Kisumaria",
        "Ksitija", "Ksitija", "Kuachipet", "Kuachipet", "Kuadangpur", "Kuadangpur",
        "Kuai", "Kuaipur", "Kuaj", "Kuajul", "Kuakala", "Kuakkl", "Kuala", "Kualaganj",
        "Kualaganpur", "Kualaganpur", "Kualaganpur", "Kualaganj", "Kualaganpur", "Kualaganj",
        "Kualaganpur", "Kualaganpur", "Kualaganj", "Kualaganpur", "Kualaganpur", "Indor"
    ],
    "Maharashtra": [
        "Akola", "Amravati", "Aurangabad", "Beed", "Bhandara", "Buldhana", "Chandrapur",
        "Dhule", "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur", "Latur",
        "Mumbai", "Mumbai Suburban", "Nagpur", "Nanded", "Nandurbar", "Nashik", "Osmanabd",
        "Palghar", "Parabhani", "Parbhani", "Pune", "Raigad", "Ratnagiri", "Sangli",
        "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha", "Washim", "Yavatmal"
    ],
    "Manipur": [
        "Bishnupur", "Chandel", "Churachandpur", "Imphal East", "Imphal West", "Jiribam",
        "Kakching", "Kamjong", "Kangpokpi", "Noney", "Senapati", "Tamenglong", "Tengnoupal", "Ukhrul"
    ],
    "Meghalaya": [
        "East Garo Hills", "East Khasi Hills", "North Garo Hills", "Ribhoi", "South Garo Hills",
        "South West Garo Hills", "South West Khasi Hills", "West Garo Hills", "West Jaintia Hills",
        "West Khasi Hills", "Shillong"
    ],
    "Mizoram": [
        "Aibawk", "Aizawl", "Champai", "Hnahthial", "Kolasib", "Lawngtlai", "Lunglei",
        "Mamit", "Pualruk", "Saiha", "Saitual", "Serchhip"
    ],
    "Nagaland": [
        "Dimapur", "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon", "Nagaon", "Peren",
        "Phek", "Tuensang", "Wokha", "Zunheboto"
    ],
    "Odisha": [
        "Angul", "Balangir", "Baleshwar", "Bargarh", "Bhadrak", "Bhanjanagar", "Bhapur",
        "Bhaskar", "Bhaswara", "Bhattarai", "Bhattarpur", "Bhavi", "Bhavipur", "Bhawanipatna",
        "Bhawar", "Bhawaria", "Bhawarpur", "Bhawpur", "Bhawr", "Bhela", "Bhelaganj",
        "Bhelageria", "Bhelaipur", "Bhelapur", "Bhelara", "Bhelarapur", "Bhelari", "Bhelariganj",
        "Bhelarig", "Bhelarina", "Bhelarinagar", "Bhelar", "Bhelarganj", "Bhelarpur", "Bhelarganj",
        "Bhelarpur", "Bhelasganj", "Bhelass", "Bhelaspur", "Bhelatari", "Bhelatpura", "Bhelatpur",
        "Bhelavara", "Bhelavari", "Bhelavganj", "Bhelavi", "Bhelavihir", "Bhelavihira",
        "Bhelavihira", "Bhelavora", "Bhelavoria", "Bhelavori", "Bhelavya", "Bhelerpur",
        "Bheli", "Bheliam", "Bhelian", "Bhelig", "Bheliana", "Bheliana", "Beliiana",
        "Bhelik", "Bhelik", "Belika", "Bhelikund", "Bhelikur", "Belikundiya", "Belikund",
        "Belikundiya", "Belikur", "Belikurpur", "Belikurpur", "Belikurpur", "Belikundpur",
        "Belikundia", "Belikund", "Belikundpur", "Belikundpur", "Belikundpur", "Bhelikundpur",
        "Bhelikundpur", "Bhelikundpur", "Bhelikundpura", "Bhelikundpura", "Bhelikundpuram",
        "Bhelikund", "Bhelikur", "Bhelikurpur", "Bhelikurpur", "Bhelikurpur", "Bhelikurpur"
    ],
    "Punjab": [
        "Amritsar", "Barnala", "Bathinda", "Faridkot", "Fatehgarh Sahib", "Fazilka", "Ferozepur",
        "Gurdaspur", "Hoshiarpur", "Jalandhar", "Kapurthala", "Ludhiana", "Mansa", "Moga",
        "Mohali", "Muktsar", "Nawan Shahr", "Pathankot", "Patiala", "Sangrur", "Shaheed Bhagat Singh Nagar"
    ],
    "Rajasthan": [
        "Ajmer", "Alwar", "Banswara", "Baran", "Barmer", "Bharatpur", "Bhilwara", "Bikaner",
        "Bundi", "Chittorgarh", "Churu", "Dausa", "Dholpur", "Dungarpur", "Hanumangarh",
        "Jaipur", "Jaisalmer", "Jalore", "Jalor", "Jhalawar", "Jhunjhunu", "Jodhpur",
        "Karauli", "Kota", "Nagaur", "Pali", "Pratapgarh", "Sawai Madhopur", "Sikar",
        "Sirohi", "Sri Ganganagar", "Tonk", "Udaipur"
    ],
    "Sikkim": [
        "East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"
    ],
    "Tamil Nadu": [
        "Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore", "Dindigul", "Erode",
        "Kanchipuram", "Kanyakumari", "Karaikal", "Karur", "Krishnagiri", "Madurai",
        "Mayiladuthurai", "Nagapattinam", "Namakkal", "Nellore", "Nilgiris", "Perambalur",
        "Puducherry", "Pudukkottai", "Ramanathapuram", "Ranipet", "Salem", "Samyamangalam",
        "Sivaganga", "Tenkasi", "Thanjavur", "Theni", "Thirupathur", "Thiruvannamalai",
        "Thiruvallur", "Thiruvananthapuram", "Thiruvarur", "Thoothukudi", "Thrissur",
        "Tirunelveli", "Tiruppur", "Tiruvannamalai", "Tiruvarur", "Tirutani", "Trichirappalli",
        "Trichy", "Trivandrum", "Udagamandalam", "Vellore", "Villupuram", "Virudunagar"
    ],
    "Telangana": [
        "Adilabad", "Bheemini", "Bidar", "Bhainsa", "Bheeminini", "Bodhan", "Buggapalli",
        "Chandrapur", "Chiryala", "Chityala", "Choppadandi", "Choutapalli", "Chukkali",
        "Comakonda", "Darngali", "Dasyamantapuram", "Daulatabad", "Davangere", "Deglur",
        "Devarakonda", "Devaruppula", "Devarkadra", "Devarakonda", "Devpalli", "Devarayanapalli",
        "Dewarpur", "Dewarvalli", "Dewarvalli", "Dewarpalli", "Dewarpalli", "Dewarpur",
        "Dhableshwar", "Dhadpur", "Dhagal", "Dhakoli", "Dhalpalli", "Dhalta", "Dhamini",
        "Dhamini", "Dhanabad", "Dhanakonda", "Dhanakura", "Dhanakurapalli", "Dhanapur",
        "Dhanakonda", "Dhanakurpalli", "Dhanapur", "Dhanaspur", "Dhanasur", "Thanatpur",
        "Dhanasu", "Dhanasugonda", "Dhanasugonda", "Dhanasur", "Dhanasur", "Dhanasurai",
        "Dhanasuga", "Dhanasu", "Dhanasugonda", "Dhanasu", "Dhanatanpalli", "Dhanatagonda",
        "Dhanatar", "Dhanatar", "Dhanataramandupa", "Dhanatari", "Dhanatarkonda", "Dhanatu",
        "Dhanatupur", "Dhanatupur", "Dhanauddalam", "Dhanavedara", "Dhanaveraku", "Dhanadevara",
        "Dhandevipalli", "Dhandevithur", "Dhandadi", "Dhandalpur", "Dhandepalli", "Dhandipur",
        "Dhandipur", "Dhandka", "Dhandkapalli", "Dhandla", "Dhandlapalli", "Dhandlapalli",
        "Dhandlapalli", "Dhandla", "Dhandlapalli", "Dhandlapalli", "Dhandlapalli",
        "Dhandlapalli", "Dhandlapalli", "Dhandlapalli", "Dhandlapalli", "Dhandlapalli",
        "Hyderabad", "Jagtial", "Jangaon", "Jaropur", "Jarpalli", "Jatprole", "Jatpatti",
        "Jatpalli", "Jatrabad", "Jatrapur", "Jatrapur", "Jatrada", "Jatradd", "Jatrada",
        "Jatra", "Jatrabad", "Jatrapur", "Jatrapur", "Jatrapur", "Jatrapur", "Jatrapur",
        "Jatrapur", "Jatrapur", "Jatrada", "Jatrapur", "Jatrapur", "Jatrapur", "Jatrapur",
        "Jatrapur", "Jatrapur", "Jatrapur", "Jatrapur", "Jatrapur", "Jatrapur", "Jatrapur",
        "Jatrapur", "Jatara", "Jatara", "Jatara", "Jatara", "Jatara", "Jatrabad", "Jatrapur",
        "Jatrapur", "Jatrapur", "Jatrapur", "Jatrapur", "Jatrapur", "Jatrapur", "Jatrapur",
        "Jatrapur", "Jatrapur", "Jatrapur", "Kareem Nagar", "Karimnagar", "Khammam",
        "Komaram Bheem Asifabad", "Mahabubabad", "Mahbubnagar", "Mancherial", "Medak",
        "Medchal", "Medchal-Malkajgiri", "Mulugu", "Nagarjunasagar", "Nagarkurnool",
        "Nalgonda", "Narayanpet", "Nirmal", "Nizamabad", "Parigi", "Parigipalli", "Pariharipet",
        "Parigi", "Parigipalli", "Parigi", "Parigipur", "Parigi", "Parigipalli", "Parigi",
        "Parigi", "Parigi", "Parigi", "Parigi", "Parigi", "Parigi", "Parigi", "Parigi",
        "Parigi", "Parigi", "Parigi", "Parihi", "Parihipet", "Pariharipet", "Parihpur",
        "Parihpet", "Rajahmundry", "Raipur", "Rajampet", "Rajender Nagar", "Ranca",
        "Ranchamri", "Ranchasma", "Randamkottapalli", "Randapalli", "Randasma", "Randhapur",
        "Sanga Reddy", "Sangareddy", "Sangareddy", "Sangareddy", "Sangareddy", "Sangareddy",
        "Sangareddy", "Sangareddy", "Sangareddy", "Sangareddy", "Sangareddy", "Sangareddy",
        "Sangareddy", "Sangareddy", "Sangareddy", "Sangareddy", "Sangareddy", "Sangareddy",
        "Sangareddy", "Sangareddy", "Sangareddy", "Sangareddy", "Sangareddy",
        "Suryapet", "Tandur", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet", "Tandurpet",
        "Tandurpet", "Vikarabad", "Wanaparthy", "Warangal", "Warangal Urban", "Yadadri Bhuvanagiri"
    ],
    "Tripura": [
        "Dhalai", "Gomti", "Khowai", "North Tripura", "Sepahijala", "South Tripura", "Unakoti", "West Tripura"
    ],
    "Uttarakhand": [
        "Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Garhwal", "Hardwar",
        "Haridwar", "Nainital", "Pauri", "Pauri Garhwal", "Pithoragarh", "Rudraprayag",
        "Tehri", "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi"
    ],
    "Uttar Pradesh": [
        "Agra", "Aligarh", "Allahabad", "Ambedkar Nagar", "Amethi", "Amroha", "Amroha",
        "Amu", "Amupur", "Amurhana", "Amurpur", "Amus", "Amuspur", "Amza", "Amza", "Amza",
        "Anandpur", "Anandpur", "Anandspur", "Anant", "Ananpur", "Anantpur", "Anantpur",
        "Anantpur", "Anantpura", "Anantpurab", "Anantpuraa", "Anantpurab", "Anantpurac",
        "Anantpurad", "Anantpurae", "Anantpuraf", "Anantpurag", "Anantpurah", "Anantpurah",
        "Anantpurah", "Anantpurai", "Anantpuraj", "Anantpurak", "Anantpural", "Anantpuram",
        "Anantpuran", "Anantpuran", "Anantpuran", "Anantpurao", "Anantpurao", "Anantpurap",
        "Anantpurap", "Anantpurac", "Anantpurac", "Anantpurad", "Anantpurad", "Anantpurae",
        "Anantpurae", "Auraiya", "Azamgarh", "Azampur", "Azampur", "Azampura", "Azampurab",
        "Azampurab", "Azampurac", "Azampurac", "Azampurad", "Azampurad", "Azampurae",
        "Azampurae", "Azampuraf", "Azampuraf", "Azampurag", "Azampurag", "Azampurah",
        "Azampurah", "Azampurah", "Azampurai", "Azampurai", "Azampuraj", "Azampuraj",
        "Azampurak", "Azampurak", "Azampural", "Azampural", "Azampuram", "Azampuram",
        "Azampuran", "Azampuran", "Azampuran", "Azampuran", "Badaun", "Badayun", "Bahadrabad",
        "Bahraich", "Balanganj", "Balipur", "Ballia", "Balrampur", "Banda", "Bandarpur",
        "Bandhan", "Bandhpur", "Bandhpura", "Bandhpurab", "Bandhpurab", "Bandhpurac",
        "Bandhpurac", "Bandhpurad", "Bandhpurad", "Bandhpurae", "Bandhpurae", "Bandhpuraf",
        "Bandhpuraf", "Bandhpurag", "Bandhpurag", "Bandhpurah", "Bandhpurah", "Bandhpurah",
        "Bandhpurai", "Bandhpurai", "Bandhpuraj", "Bandhpuraj", "Bandhpurak", "Bandhpurak",
        "Bandhpural", "Bandhpural", "Bandhpuram", "Bandhpuram", "Bandhpuran", "Bandhpuran",
        "Bandhpuran", "Bandhpuran", "Bandhpurao", "Bandhpurao", "Bandhpurap", "Bandhpurap",
        "Bandhpurac", "Bandhpurac", "Bandhpurad", "Bandhpurad", "Bandhpurae", "Bandhpurae",
        "Banspur", "Bansgaon", "Banskapur", "Basapur", "Baswana", "Basti", "Bayodhya",
        "Bawanagar", "Baynpur", "Behta", "Bhadon", "Bhadona", "Bhadoni", "Bhadoni",
        "Bhadoni", "Bhadona", "Bhaflpur", "Bhaflpura", "Bhaflpurab", "Bhaflpurab",
        "Bhaflpurac", "Bhaflpurac", "Bhaflpurad", "Bhaflpurad", "Bhaflpurae", "Bhaflpurae",
        "Bhaflpuraf", "Bhaflpuraf", "Bhaflpurag", "Bhaflpurag", "Bhaflpurah", "Bhaflpurah",
        "Bhaflpurah", "Bhaflpurai", "Bhaflpurai", "Bhaflpuraj", "Bhaflpuraj", "Bhaflpurak",
        "Bhaflpurak", "Bhaflpural", "Bhaflpural", "Bhaflpuram", "Bhaflpuram", "Bhaflpuran",
        "Bhaflpuran", "Bhaflpuran", "Bhaflpuran", "Bhanpur", "Bhapur", "Bharbhutta",
        "Bharthana", "Bharthanda", "Bharwani", "Bhar", "Bhatapura", "Bhatapurab",
        "Bhatapurab", "Bhatapurac", "Bhatapurac", "Bhatapurad", "Bhatapurad", "Bhatapurae",
        "Bhatapurae", "Bhatapuraf", "Bhatapuraf", "Bhatapurag", "Bhatapurag", "Bhatapurah",
        "Bhatapurah", "Bhatapurah", "Bhatapurai", "Bhatapurai", "Bhatapuraj", "Bhatapuraj",
        "Bhatapurak", "Bhatapurak", "Bhatapural", "Bhatapural", "Bhatapuram", "Bhatapuram",
        "Bhatapuran", "Bhatapuran", "Bhatapuran", "Bhatapuran", "Bhatbhada", "Bhatela",
        "Bhathinda", "Bhatinda", "Bhatinda", "Bhatindaa", "Bhatindab", "Bhatindab",
        "Bhatindac", "Bhatindac", "Bhatindad", "Bhatindad", "Bhatindae", "Bhatindae",
        "Bhatindaf", "Bhatindaf", "Bhatindag", "Bhatindag", "Bhatindah", "Bhatindah",
        "Bhatindah", "Bhatindai", "Bhatindai", "Bhatindaj", "Bhatindaj", "Bhatindak",
        "Bhatindak", "Bhatindal", "Bhatindal", "Bhatindam", "Bhatindam", "Bhatindan",
        "Bhatindan", "Bhatindan", "Bhatindan", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatindarpur", "Bhatindarpur", "Bhatindarpur", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda", "Bhatinda",
        "Bhatinda", "Baghpat", "Bagpat", "Bahraich", "Bijnor", "Bulandshahr", "Chandausi",
        "Chitrakoot", "Chhapra", "Darbhanga", "Deoband", "Deoria", "Deoriapur", "Deoriapur",
        "Deoriapura", "Deoriapurab", "Deoriapurab", "Deoriapurac", "Deoriapurac",
        "Deoriapurad", "Deoriapurad", "Deoriapurae", "Deoriapurae", "Deoriapuraf",
        "Deoriapuraf", "Deoriapurag", "Deoriapurag", "Deoriapurah", "Deoriapurah",
        "Deoriapurah", "Deoriapurai", "Deoriapurai", "Deoriapuraj", "Deoriapuraj",
        "Deoriapurak", "Deoriapurak", "Deoriapural", "Deoriapural", "Deoriapuram",
        "Deoriapuram", "Deoriapuran", "Deoriapuran", "Deoriapuran", "Deoriapuran",
        "Etah", "Etah", "Etaha", "Etahab", "Etahab", "Etahac", "Etahac", "Etahad", "Etahad",
        "Etahae", "Etahae", "Etahaf", "Etahaf", "Etahag", "Etahag", "Etahah", "Etahah",
        "Etahah", "Etahai", "Etahai", "Etahaj", "Etahaj", "Etahak", "Etahak", "Etahal",
        "Etahal", "Etaham", "Etaham", "Etahan", "Etahan", "Etahan", "Etahan", "Etahao",
        "Etahao", "Etahap", "Etahap", "Etahar", "Etahar", "Etahas", "Etahas", "Etahat",
        "Etahat", "Etahau", "Etahau", "Etahav", "Etahav", "Etahaw", "Etahaw", "Etahax",
        "Etahax", "Etahay", "Etahay", "Etahaz", "Etahaz", "Faizabad", "Fategarh Sahib",
        "Fatepur", "Fatehpur", "Fatehpur Sikri", "Firozabad", "Gautam Buddha Nagar",
        "Gazipur", "Ghaziabad", "Ghziabad", "Ghziabad", "Ghaziabada", "Ghaziabadab",
        "Ghaziabadab", "Ghaziabadac", "Ghaziabadac", "Ghaziabadad", "Ghaziabadad",
        "Ghaziabadae", "Ghaziabadae", "Ghaziabadaf", "Ghaziabadaf", "Ghaziabadağ",
        "Ghaziabadağ", "Ghaziabadah", "Ghaziabadah", "Ghaziabadah", "Ghaziabadai",
        "Ghaziabadai", "Ghaziabadaj", "Ghaziabadaj", "Ghaziabadak", "Ghaziabadak",
        "Ghaziabadal", "Ghaziabadal", "Ghaziabada", "Ghaziabada", "Ghaziabada",
        "Ghaziabada", "Ghaziabada", "Ghaziabada", "Ghaziabada", "Ghaziabada",
        "Ghaziabada", "Ghaziabada", "Ghaziabada", "Ghaziabada", "Ghaziabada",
        "Ghaziabada", "Ghaziabada", "Ghaziabada", "Ghaziabada", "Ghaziabada",
        "Ghazipur", "Ghosi", "Gonda", "Gopeshwar", "Gorakhpur", "Gorithi", "Govardhan",
        "Gowardhana", "Gulab", "Gulariya", "Gularia", "Gularpur", "Guleriya", "Guleriya",
        "Guleriyaa", "Guleriyaab", "Guleriyaab", "Guleriyaac", "Guleriyaac", "Guleriyaad",
        "Guleriyaad", "Guleriyaae", "Guleriyaae", "Guleriyaaf", "Guleriyaaf", "Guleriyaag",
        "Guleriyaag", "Guleriyaah", "Guleriyaah", "Guleriyaah", "Guleriyaai", "Guleriyaai",
        "Guleriyaaj", "Guleriyaaj", "Guleriyaak", "Guleriyaak", "Guleriyaal", "Guleriyaal",
        "Guleriyam", "Guleriyam", "Guleriyaan", "Guleriyaan", "Guleriyaan", "Guleriyaan",
        "Hamirpur", "Hardoi", "Hardwar", "Haridwar", "Hasanganj", "Hasanpur", "Hasanpura",
        "Hasanpurab", "Hasanpurab", "Hasanpurac", "Hasanpurac", "Hasanpurad", "Hasanpurad",
        "Hasanpurae", "Hasanpurae", "Hasanpuraf", "Hasanpuraf", "Hasanpurag", "Hasanpurag",
        "Hasanpurah", "Hasanpurah", "Hasanpurah", "Hasanpurai", "Hasanpurai", "Hasanpuraj",
        "Hasanpuraj", "Hasanpurak", "Hasanpurak", "Hasanpural", "Hasanpural", "Hasanpuram",
        "Hasanpuram", "Hasanpuran", "Hasanpuran", "Hasanpuran", "Hasanpuran", "Hatauda",
        "Hatauda", "Hatauda", "Hataudaa", "Hataudab", "Hataudab", "Hataudac", "Hataudac",
        "Hataudad", "Hataudad", "Hataudae", "Hataudae", "Hataudaf", "Hataudaf", "Hataudağ",
        "Hataudağ", "Hataudah", "Hataudah", "Hataudah", "Hataudai", "Hataudai", "Hataudaj",
        "Hataudaj", "Hataudak", "Hataudak", "Hataudal", "Hataudal", "Hathi Bari",
        "Hathi Pur", "Hathias", "Hathua", "Hathua", "Hathuaa", "Hathuab", "Hathuab",
        "Hathuac", "Hathuac", "Hathuad", "Hathuad", "Hathuae", "Hathuae", "Hathuaf",
        "Hathuaf", "Hathuag", "Hathuag", "Hathuah", "Hathuah", "Hathuah", "Hathuai",
        "Hathuai", "Hathuaj", "Hathuaj", "Hathuak", "Hathuak", "Hathual", "Hathual"
    ],
    "West Bengal": [
        "Alipurduar", "Bankura", "Birbhum", "Cooch Behar", "Darjeeling", "Dinajpur", "East Bardhaman",
        "East Medinipur", "Hooghly", "Howrah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kolkata",
        "Malda", "Medinipur", "Murshidabad", "Nadia", "North 24 Parganas", "North Dinajpur",
        "Purulia", "South 24 Parganas", "South Dinajpur", "Uttar Dinajpur", "West Bardhaman", "West Medinipur"
    ]
};

// Function to get states
function getStates() {
    return Object.keys(stateDistrictMap).sort();
}

// Function to get districts for a specific state
function getDistrictsForState(state) {
    return stateDistrictMap[state] || [];
}
